language: python
python:
  - "3.6"

addons:
  rethinkdb: "2.3"

branches:
  only:
    - "master"

sudo: required

services:
  - docker

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync --dev

script:
  - pipenv run lint
# - pipenv run test
  
after_success:
  - bash scripts/deploy.sh
  - chmod +x scripts/discord_webhook.sh
  - ./scripts/discord_webhook.sh success $DISCORD_WEBHOOK_URL

after_failure:
  - chmod +x scripts/discord_webhook.sh
  - ./scripts/discord_webhook.sh failure $DISCORD_WEBHOOK_URL

cache: pip

notifications:
  email: false
